### ISSUE TITLE
C Drive sizes incorrect

### ISSUE THREAD

**Issue by Eaglehawk48** [codaamok/PoSH#4]
Using the current version of AutomatedLab 5.19.0 and your current (10th April 2020) script, the disk size of C isn't 100GB as documented (and coded) but only 50GB (the default size if not specified). I tried to find where it's failing to pass on the 100GB disk size, but I can't find any obvious fault in your CM-1902.ps1 script. Is this more of a AutomatedLab bug?

The issue only comes to a head when you run the update SCCM portion, it fails the pre-req diskspace check as the C drive is almost full on CM01. I've gotten around it by manually expanding the C drive in HyperV to 100GB and extending the partition during the SCCM update cycle.

**Comment by codaamok** [comment]
I don't think I've seen that, but I'm running a build now to double check. 

Do you happen to know if, when you ran this script, you already had reference/base disks created or were new ones created when you ran `CM-1902.ps1`?

Could well be a bug in AutomatedLab, which I'll be up for fixing. We'll see.

**Comment by Eaglehawk48** [comment]
I was following your winadmins blogs, so I did build one lab first before hitting your CM-1902.ps1 script. Then had all those issues with the AutomatedLabSQL.psm1 problems before getting to this one which I couldn't work out! So it could be an initial build image issue...

**Comment by codaamok** [comment]
OK thanks. I'll have a fiddle and let you know.

For the AutomatedLabSQL.psm1 issues, you're probably referring to this: https://github.com/AutomatedLab/AutomatedLab/pull/857

You'll either need to modify AutomatedLabSQL.psm1 locally on your machine with the change in that link, or wait until next AutomatedLab version, or pull the AutomatedLab repo 😄 

Thank you very much for taking the time to let me know though 😄 main reason for me doing this was to help people and being notified of issues helps me make it better.

**Comment by Eaglehawk48** [comment]
Yep, I've done those fixes already locally :)

The next bug after this one is fixed is the use of SQL ISO images. I'll post that later this week. The auto download seems to have stopped working, (of the SQL 2017 eval version), but the script also errored when using the en_sql_server_2017_standard_x64_dvd_11294407.iso image. I haven't looked into the code for that yet either. Thanks for your hard work!

**Comment by codaamok** [comment]
OK, looks like you need to delete your original reference disk first. 

I'll have a stab at a solution for AutomatedLab, you can track the discussion for that here which I've just created in their repo: https://github.com/AutomatedLab/AutomatedLab/issues/862

**Comment by codaamok** [comment]
As for the SQL URL, works OK for me: https://download.microsoft.com/download/5/2/2/522EE642-941E-47A6-8431-57F0C2694EDF/SQLServer2017-SSEI-Eval.exe

Does it not for you?

**Comment by Eaglehawk48** [comment]
That download part worked. It's the part that had to then run to extract the ISO that failed. I didn't catch the error messages though. I did try to run it manually, and it also failed. I just got the ISO following this link:

https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SQLServer2017-x64-ENU.iso

**Comment by Eaglehawk48** [comment]
Happy to close this issue now that I know the solution and it's being submitted to AutomatedLab.

**Comment by codaamok** [comment]
I'm going to keep open for now until it's resolved, just in case anyone else comes across it and comes here to open an issue 😄

**Comment by Eaglehawk48** [comment]
Good point. While we're discussing this case, another thing I've realised.

I used CM-1902.ps1 to create a second lab instance of SCCM. It worked of course. During the course of doing this, and fixing this issue. I renamed the basedisk and created your standard DC01/CM01 servers. Obviously, my second lab instance died (because the base disk now doesn't match). Fair enough. I should have merged the disk before I deleted the base disk right? *DOH*

However, I've now realised that I cannot have two labs running at the same time, as the two disk files:

CM01-DATA-01
CM01-SQL-01

Would be used by both labs. Is that correct? I didn't test my theory because by then, my 2nd lab had gotten corrupted when I deleted the base disk!

Would it be possible to make these disks be named $CMLabName or even $CMHostname so that I can have two labs running at the same time? :D

I guess I could just edit everything after the 1st build and then start the 2nd build with no issues?

**Comment by codaamok** [comment]
Excellent point, I completely overlooked that. I've just pushed a commit w/ your idea. Thanks!

**Comment by Eaglehawk48** [comment]
Doh, you beat me to it! :)

Add-LabDiskDefinition -Name "$CMHostname-DATA-01" -DiskSizeInGb 50 -Label "DATA01" -DriveLetter "G"
Add-LabDiskDefinition -Name "$CMHostname-SQL-01" -DiskSizeInGb 30 -Label "SQL01" -DriveLetter "F"

Plus a few other lines...running a second lab build now, but it will take 1h 40 mins before I find out whether I stuffed anything up :)

**Comment by Eaglehawk48** [comment]
You may need to also update lines 464 and 482...for consistency :)

**Comment by codaamok** [comment]
Nice catch, thanks 😄

**Comment by codaamok** [comment]
The reference disk size change issue has been addressed: https://github.com/AutomatedLab/AutomatedLab/issues/862

Not sure if it's 5.21.0 but it should definitely be in the subsequent release if not.
